sa_events:
  source: 'https://github.com/harsha070/data-pipeline/blob/048d989b592c374d4b88bb878fac3c08d3b73c64/data/sa_events.xlsx'
  source_type: 'dynamic'
bmt_events:
  source: 'https://github.com/harsha070/data-pipeline/blob/048d989b592c374d4b88bb878fac3c08d3b73c64/data/bmt_events.tsv'
  source_type: 'dynamic'
fsym: 'https://github.com/harsha070/data-pipeline/blob/048d989b592c374d4b88bb878fac3c08d3b73c64/data/fsym_to_ticker.tsv'

# Define your AWS credentials
aws:
  access_key: 'admin'
  secret_key: 'password'

cron_frequency: 30 # minutes
